@startuml
left to right direction   

[*] --> メニュー 
メニュー --> [*]

メニュー --> 予約と確認 :予約登録する
予約と確認 --> あなたの順番 :順番の確認
予約と確認 --> あなたの順番 :登録後

予約と確認 --> メニュー :予約取り消し

メニュー --> 今の順番
今の順番 --> メニュー :戻る
あなたの順番 --> メニュー :戻る
@enduml