@startuml ライントレーサー
class ライントレーサー {
- 名前:String
}

class 光センサー {
+ ライン判断
+ 取り付ける
}

class 右モーター {
+ 取り付ける
+ 動く
}

class 左モーター {
+ 取り付ける
+ 動く
}
class CPU {
- 名前:String
- 大きさ:String
+ 処理
}
class 電源SW {
- 名前:String
+ ONOFF: int
}
ライントレーサー "1" <-- "1" 光センサー :装着 >
ライントレーサー "1" <-- "1" 右モーター :装着 >
ライントレーサー "1" <-- "1" 左モーター :装着 >
ライントレーサー "1" <-- "1" CPU :装着 >
ライントレーサー "1" <-- "1" 電源SW :装着 >
@enduml