@startuml ユースケース図
left to right direction

    actor 利用者学生
    actor 先生
    actor サークルリーダー
rectangle サークル活動サイト {

    usecase サークル立ち上げ申請
    usecase サークル立ち上げ
    usecase サークル参加申請
    usecase 活動記録
    usecase サークル参加
    usecase 見学

    利用者学生 --> サークル立ち上げ申請
    利用者学生 -> サークル参加
    利用者学生 --> 見学
    サークルリーダー --> 活動記録
    サークルリーダー --> サークル管理
    先生 --> サークル立ち上げ
    先生 --> サークル管理
        サークル参加申請 <. サークル参加 : <<include>>
        サークル立ち上げ申請 --> 先生

    package サークル管理{
        usecase サークル削除
        usecase サークル編集
    }
    }
rectangle スラック {
    actor 利用者学生
    usecase チャット
    usecase 新サークル設立通知

    利用者学生 <--> チャット
    新サークル設立通知 --> 利用者学生
} 
サークル参加申請 --> サークルリーダー

@endumll