@startuml
object "<u>利用者A: 利用者リスト</u>" as r1 {
名前
チェックイン日=5/3
泊数=2
}
object "<u>利用者B: 利用者リスト</u>" as r2 {
名前
チェックイン日=5/3
泊数=2
}
object "<u>301号室: 客室リスト</u>" as k1 {
タイプ=シングル
キャンペーン期間=4/29~5/6
キャンペーン価格=9000
}
object "<u>302号室: 客室リスト</u>" as k2 {
タイプ=シングル
キャンペーン期間=4/29~5/6
キャンペーン価格=9000
}
object "<u>303号室: 客室リスト</u>" as k3 {
タイプ=シングル
キャンペーン期間=4/29~5/6
キャンペーン価格=9000
}
r1 "1"-->"1" k1:宿泊する
r2 "1"-->"1" k3:宿泊する
@enduml