@startuml カレーライス
title カレーライスの作り方
start
:材料を用意する;
:米を研ぐ;
fork
    :米を炊く;
    :ライス]
    fork again
    :具材を切る;
    :具材を炒める;
    :炒めたものとカレールーなど必要なものを混ぜる;
    :カレー]
end fork

:盛り付ける;
:カレーライス]
stop
@enduml