@startuml 診療記録
class 病院 {
- 医局:String
}
class 担当医 {
- 名前:String
- 所属科:String
+ 治療
}
class 患者 {
- 名前:String

}
class 診察記録 {
- 患者名:String
- 診察日:String
- 診断:String
- 処方箋:String
}
病院 "1"-->"*" 担当医:""雇う >
担当医 "1"-->"*" 患者:診察する >
担当医 "1"--> "*"診察記録:作成 >
@enduml