@startuml 演習4-2
hide footbox
 'メッセージに自動で番号を降る
 autonumber
' 厳密なUMLに準拠する
skinparam style strictuml
actor "<u>user:利用者</u>" as user
participant "<u>:予約画面</u>" as yoyaku

    activate user
        user ->> yoyaku: ログイン()（予約画面にログインメッセージを送る） 
        note right of user:非同期メッセージ
        activate yoyaku
            yoyaku -> yoyaku: 認証()
            yoyaku -> user: ログイン成功通知
            note right of yoyaku: 再帰呼び出し
        deactivate yoyaku
    deactivate user


@enduml